[package]
org = "ballerina"
name = "oauth2"
version = "2.4.0"
authors = ["Ballerina"]
keywords = ["security", "authorization", "introspection"]
repository = "https://github.com/ballerina-platform/module-ballerina-oauth2"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "oauth2-native"
version = "2.4.0"
path = "../native/build/libs/oauth2-native-2.4.0-SNAPSHOT.jar"
