[package]
org = "ballerina"
name = "oauth2"
version = "2.12.0"
authors = ["Ballerina"]
keywords = ["security", "authorization", "introspection"]
repository = "https://github.com/ballerina-platform/module-ballerina-oauth2"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "oauth2-native"
version = "2.12.0"
path = "../native/build/libs/oauth2-native-2.12.0.jar"
