name: Trigger load tests

on:
  workflow_dispatch:
    inputs:
      tests:
        description: >
          List of test names. This needs to be filled only if you want to run a specific set of tests. Example: foo,bar
        required: false
      clusterName:
        description: 'Cluster name'
        default: 'oauth2-perf-cluster-test'
        required: false
  schedule:
    - cron: '30 16 * * *'

jobs:
  call_stdlib_trigger_load_test_workflow:
      name: Run StdLib Load Test Workflow
      if: ${{ github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository_owner == 'ballerina-platform') }}
      uses: ballerina-platform/ballerina-library/.github/workflows/trigger-load-tests-template.yml@java21
      with:
        repo_name: 'module-ballerina-oauth2'
        runtime_artifacts_url: 'https://api.github.com/repos/ballerina-platform/module-ballerina-oauth2/actions/artifacts'
        dispatch_type: 'oauth2-load-test'
        cluster_name: ${{ inputs.clusterName }}
        tests: ${{ inputs.tests }}
        branch: ${{ inputs.branch }}
      secrets:
        ballerina_bot_token: ${{ secrets.BALLERINA_BOT_TOKEN }}
